# This runs after changes are merged to `master`.
name: Update Website
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
  schedule:
    # Daily at 8:20 UTC
    - cron: '20 8 * * *'
env:
  WEB_APP_PATH: "apps/wp_example"
  PUBLIC_WEB_DIR: "apps/wp_example/public"
  WP_DIR_PATH: "apps/wp_example/public/wp"
  APP_CONTENT_DIR: "apps/wp_example/public/app"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ${{ env.WEB_APP_PATH }} && ls -l -a
          mv composer.lock storage/logs/updates/composer.$(date +%Y%m%d_%H%M%S).txt && composer install
